
---
- name: Ensure dependencies are installed.
  apt:
    name:
      - curl
      - apt-transport-https
    state: present

- name: Add Jenkins apt repository key.
  apt_key:
    url: "{{ jenkins_repo_key_url }}"
    state: present

- name: Add Jenkins apt repository.
  apt_repository:
    repo: "{{ jenkins_repo_url }}"
    state: present
    update_cache: true
  when: jenkins_repo_url != ""
  tags: ['skip_ansible_lint']


- name: Install jenkins
  apt:
    name : jenkins
    state: present
    update_cache: yes



- name: Ensure Jenkins is started and runs on startup.
  service: name=jenkins state=started enabled=yes
