{
 "title": "Kubernetes Apps",
 "tags": [
  "kubernetes",
  "apps"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "container_cpu_user_seconds_total"
   },
   {
    "name": "app",
    "label": "App",
    "query": "kube_deployment_created{exported_namespace=\"$namespace\"}"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "kube_pod_container_info{exported_namespace=\"$namespace\",pod=~\"$app.*\"}"
   }
  ]
 },
 "panels": [
  { "title": "CPU/Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate (container_cpu_usage_seconds_total{id!=\"\", namespace=\"$namespace\",pod_name=~\"$app.*\",pod_name=~\"$pod.*\"}[1m]) * 100) by (pod_name) ",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{name!~\"POD\",namespace=\"$namespace\", pod_name=~\"$app.*\",pod_name=~\"$pod.*\"}) by (pod_name) / sum(container_spec_memory_limit_bytes{name!~\"POD\",namespace=\"$namespace\",pod_name=~\"$app.*\",pod_name=~\"$pod.*\"}) by (pod_name)) *100",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  { "title": "JMX", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Heap usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{app_name=\"$app\",pod_name=~\"$pod.*\"}",
     "legendFormat": "{{ area }}-{{ id}}-{{ pod_name }}"
    }
   ]
  },
  {
   "title": "GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_pause_seconds_count{app_name=\"$app\", pod_name=~\"$pod.*\"}",
     "legendFormat": "{{ action }}-{{ cause }}: {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Threads Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live_threads{app_name=\"$app\", pod_name=~\"$pod.*\"}",
     "legendFormat": "JVM - {{pod_name}}"
    },
    {
     "expr": "tomcat_threads_busy_threads{app_name=\"$app\", pod_name=~\"$pod.*\"}",
     "legendFormat": "Tomcat Busy - {{pod_name}}"
    },
    {
     "expr": "tomcat_threads_current_threads{app_name=\"$app\", pod_name=~\"$pod.*\"}",
     "legendFormat": "Tomcat Current - {{pod_name}}"
    },
    {
     "expr": "tomcat_threads_config_max_threads{app_name=\"$app\", pod_name=~\"$pod.*\"}",
     "legendFormat": "Tomcat Max - {{pod_name}}"
    }
   ]
  },
  { "title": "Autoscaling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Active Replicas",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kube_hpa_status_current_replicas{exported_namespace=\"$namespace\",hpa=\"$app\"})",
     "legendFormat": "replicas"
    }
   ]
  },
  {
   "title": "Limits-Min",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 41 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kube_hpa_spec_min_replicas{exported_namespace=\"$namespace\",hpa=\"$app\"})"
    }
   ]
  },
  {
   "title": "Limits-Max",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 41 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kube_hpa_spec_max_replicas{exported_namespace=\"$namespace\",hpa=\"$app\"})"
    }
   ]
  }
 ]
}