- name: Install Java
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
    force_apt_get: true
  retries: 3
  with_items: "{{ java_packages }}"
  tags:
    - java

- name: Set JAVA_HOME if configured
  template:
    src: java_home.sh.j2
    dest: /etc/profile.d/java_home.sh
    mode: 0644
  tags:
    - java
