---
- name: Add Ansible repository
  apt_repository:
    repo: ppa:ansible/ansible
    state: present
- name: Update apt respository
  apt:
    update_cache=yes
- name: Install Ansible packages
  apt:
    name: ansible
    state: present
    
