# IBM Guestbook image version ibmcom/guestbook:v1
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ibmcom/guestbook
  tag: v1
  pullPolicy: Always

# For some dev env (like minikube), you may need to set the type to NodePort
service:
  type: NodePort
  httpPort: 80
  redisMasterPort: 6379
  redisSlavePort: 6379
redis:
  port: 6379 
  slaveEnabled: true

