- name: Create prometheus datasource
  grafana_datasource:
    name: "prometheus"
    grafana_url: "http://localhost:3000"
    grafana_user: "admin"
    grafana_password: "{{ grafana_admin_password | default('admin') }}"
    org_id: "1"
    ds_type: "prometheus"
    url: "http://localhost:9090"
    time_interval: ">10s"
