---
- hosts: bastion
  gather_facts: no
  tasks:
    - name: Wait for SSH to come up
      wait_for_connection:
        timeout: 600

- hosts: bastion

  become: yes

  vars_files:
    - "./../vars/main.yml"
  tasks:
    - name:
      command: git clone https://github.com/abijithvjn/mstackx.git
      ignore_errors: yes
      args:
        chdir: /root/
  roles:
  - ansible
