---
- hosts: master
  become: yes
  gather_facts: no
  tasks:
    - name: Wait for SSH to come up
      wait_for_connection:
        timeout: 600
    - name: copy config from matches_filter
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: /tmp/kubeconfig.conf
        flat: yes
- hosts: bastion,jenkins_node
  become: yes
  vars_files:
    - "./../vars/main.yml"
  gather_facts: no
  tasks:
    - name: Wait for SSH to come up
      wait_for_connection:
        timeout: 600
  tasks:
    - name: copy config to bastion
      copy:
        src: /tmp/kubeconfig.conf
        dest: /root/.kube/config
        owner: root
        group: root
        mode: '0755'
    - name: Download kubectl
      get_url:
        url: "{{kubectl_url}}"
        dest: /usr/local/bin/kubectl
        mode: '0755'
  roles:
  - helm
