- name: Now configuring everything else :D
  hosts: bastion
  become: yes

  vars_files:
    - "./../vars/main.yml"
  tasks:
    - name: Configure jenkins
      command: ansible-playbook playbooks/jenkins.yml
      args:
        chdir: /root/mstackx/ansible
    - name: Configure elasticsearch
      command: ansible-playbook playbooks/elasticsearch.yml
      args:
        chdir: /root/mstackx/ansible
    - name: Configure kibana
      command: ansible-playbook playbooks/kibana.yml
      args:
        chdir: /root/mstackx/ansible
    - name: Configure kubernetes
      command: ansible-playbook playbooks/site.yml
      args:
        chdir: /root/mstackx/ansible
    - name: Configure kubernetes
      command: ansible-playbook playbooks/site.yml
      args:
        chdir: /root/mstackx/ansible    
    - name: Configure kubectl
      command: ansible-playbook playbooks/configure-kubectl.yml
      args:
        chdir: /root/mstackx/ansible
    - name: Configure kubernetes-apps
      command: ansible-playbook playbooks/kubernetes-apps.yml
      args:
        chdir: /root/mstackx/ansible
