---
- hosts: jenkins_node
  gather_facts: no
  tasks:
    - name: Wait for SSH to come up
      wait_for_connection:
        timeout: 20

- hosts: jenkins_node

  become: yes

  vars_files:
    - "./../vars/main.yml"

  roles:
  - java
  - jenkins
