---
- name: Wrapup ansible
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: terraform init for vpc
    command: terraform init
    ignore_errors: yes
    args:
      chdir: ./../../terraform/resources/vpc/
  - name: create resources
    command: terraform apply -lock=false -auto-approve
    ignore_errors: yes
    args:
      chdir: ./../../terraform/resources/vpc/
  - name: terraform init for all resources
    command: terraform init
    ignore_errors: yes
  - name: Spawn resources
    command: terraform apply -lock=false -auto-approve
    ignore_errors: yes
    args:
      chdir: ./../../terraform/resources/mstackx/
  - name: pause for a  minutes
    pause:
      minutes: 1
  - name: Configure bastion host
    command: ansible-playbook playbooks/bastion.yml
