apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
spec:
  ports:
  - port: {{ .Values.redis.port }}
    targetPort: {{ .Values.service.redisMasterPort }}
  selector:
    app: redis
    role: master
